## 1. What is PyTorch?

#### Importing libraries

In [44]:
from __future__ import print_function
import torch
import numpy as np

#### Table of content:
* [Introduction and random notes](#first-bullet)
    * Tensors are similar to Numpy's ndarrays --> but can be used on a GPU
    * Tensors can be recreated from other tensors using the ``new_*`` method
    
* [Tensor operations](#second-bullet)
    * There are multiple syntaxes for operations
        * Syntax 1
        * Syntax 2
        * Syntax 3
    * Any operation that mutates a tensor in-place is post-fixed with an ``_``. For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.

* [Indexing the tensors](#third-bullet)
    * 
        
* [Resize or reshape tensor](#forth-bullet)
    * ``*_view(*)`` function
    * 
* [Getting value as a number](#fifth-bullet) 
    * ``*.item()`` function for 1 element tensor
    * 
* [Converting to NumPy Array, vice versa](#sixth-bullet) 
    * 
    * 
* [Using of GPUs](#seventh-bullet)
    * The ``to`` method moves the tensors onto any device (CPU, GPU...) 
    * Keeps track of the GPU and these are 0-indexed

## Introduction and random notes <a class="anchor" id="first-bullet"></a>

#### Construct a 5 x 3 matrix, uninitialized

In [3]:
x = torch.empty(5,3) # 5 sets of [with 3 elements]
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  3.2622e-42,  0.0000e+00],
        [ 0.0000e+00,  6.8608e+22,  0.0000e+00]])


##### Construct a randomly initialized matrix

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[ 0.8935,  0.7163,  0.7133],
        [ 0.1363,  0.7012,  0.4815],
        [ 0.2288,  0.6090,  0.8284],
        [ 0.9810,  0.3910,  0.4508],
        [ 0.9512,  0.6248,  0.1261]])


##### Construct a matrix filled with zeros and of dtype float

In [5]:
x = torch.zeros(5,3, dtype = torch.float)
print(x)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])


##### Construct a matrix filled with ones and of dtype long

In [7]:
x = torch.ones(5,3, dtype = torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


##### Constructor a tensor directly from data

In [8]:
x_new = torch.tensor([[5.5,3],[4.4,3]])
print(x_new)

tensor([[ 5.5000,  3.0000],
        [ 4.4000,  3.0000]])


##### Creating a tensor based on existing tensor
##### properties are reused unless stated

##### new_* methods take in sizes

In [9]:
x_new = x.new_ones(5,3, dtype = torch.double) # new_* methods take in sizes
print(x_new)
x_new = x.new_zeros(5,3, dtype = torch.double) # new_* methods take in sizes
print(x_new)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]], dtype=torch.float64)


##### Override dtype

In [11]:
print(x)
x_new = torch.randn_like(x, dtype = torch.float) # overrides the dtype and keep the size
print(x_new)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])
tensor([[-1.1124, -0.0337,  1.2155],
        [ 1.0124,  1.5540,  0.6375],
        [-0.6025, -0.4342, -1.6678],
        [-0.7746,  0.3888,  1.2857],
        [-1.1158,  2.1800, -1.8758]])


##### Get tensor size

In [12]:
print(x.size()) # This outputs a tuple hence it supports all tuple operations

torch.Size([5, 3])


## Tensor operations <a class="anchor" id="second-bullet"></a>

In [13]:
y = torch.rand(5,3)
print("x is: ")
print(x)
print("y is: ")
print(y)

x is: 
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])
y is: 
tensor([[ 0.4644,  0.5816,  0.7418],
        [ 0.7620,  0.1233,  0.4731],
        [ 0.2915,  0.4944,  0.0507],
        [ 0.6650,  0.3723,  0.9225],
        [ 0.8933,  0.9273,  0.5051]])


##### Syntax 1 - x+y

In [17]:
print(x + y) # Element wise addition --> Hence must be same size?

print(torch.tensor([[2,3,4], [5,6,7]]) + y)

tensor([[ 1.4644,  1.5816,  1.7418],
        [ 1.7620,  1.1233,  1.4731],
        [ 1.2915,  1.4944,  1.0507],
        [ 1.6650,  1.3723,  1.9225],
        [ 1.8933,  1.9273,  1.5051]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (5) at non-singleton dimension 0

##### Syntax 2 - torch.add(x,y)

##### a.

In [18]:
print(torch.add(x,y))

tensor([[ 1.4644,  1.5816,  1.7418],
        [ 1.7620,  1.1233,  1.4731],
        [ 1.2915,  1.4944,  1.0507],
        [ 1.6650,  1.3723,  1.9225],
        [ 1.8933,  1.9273,  1.5051]])


##### b. Providing an output tensor as argument

In [19]:
result = torch.empty(5,3)
print("result")
torch.add(x,y, out = result)
print(result)

result
tensor([[ 1.4644,  1.5816,  1.7418],
        [ 1.7620,  1.1233,  1.4731],
        [ 1.2915,  1.4944,  1.0507],
        [ 1.6650,  1.3723,  1.9225],
        [ 1.8933,  1.9273,  1.5051]])


##### Syntax 3 - y.add_(x) 

##### This does in-place addition : Ie, the tensor at the front will be mutated

In [20]:
y.add_(x)
print(y)

tensor([[ 1.4644,  1.5816,  1.7418],
        [ 1.7620,  1.1233,  1.4731],
        [ 1.2915,  1.4944,  1.0507],
        [ 1.6650,  1.3723,  1.9225],
        [ 1.8933,  1.9273,  1.5051]])


## Indexing the tensors <a class="anchor" id="third-bullet"></a>

In [21]:
print("y is: ")
print(y)
print()

print("Getting the second column of all the rows: ")
print(y[:, 1]) # All rows, second column

y is: 
tensor([[ 1.4644,  1.5816,  1.7418],
        [ 1.7620,  1.1233,  1.4731],
        [ 1.2915,  1.4944,  1.0507],
        [ 1.6650,  1.3723,  1.9225],
        [ 1.8933,  1.9273,  1.5051]])

Getting the second column of all the rows: 
tensor([ 1.5816,  1.1233,  1.4944,  1.3723,  1.9273])


## Resizing or reshaping a tensor <a class="anchor" id="forth-bullet"></a>

In [32]:
x_new2 = torch.rand(4,4) # 4 * 4
print(x_new2)
print()

y_new2 = x_new2.view(16) # Compresses the tensor into a "1-d array"?
print(y_new2)
print()

z_new2 = x_new2.view(-1,8) # size -1 means that we infer this from other dimensions --> since its 8, the first size is 16/8 = 2
print(z_new2)
print()

print(x_new2.size(), y_new2.size(), z_new2.size())

tensor([[ 0.2721,  0.7503,  0.5569,  0.9770],
        [ 0.2649,  0.9712,  0.5143,  0.9589],
        [ 0.5193,  0.2695,  0.9072,  0.4709],
        [ 0.3497,  0.6431,  0.6209,  0.3219]])

tensor([ 0.2721,  0.7503,  0.5569,  0.9770,  0.2649,  0.9712,  0.5143,
         0.9589,  0.5193,  0.2695,  0.9072,  0.4709,  0.3497,  0.6431,
         0.6209,  0.3219])

tensor([[ 0.2721,  0.7503,  0.5569,  0.9770,  0.2649,  0.9712,  0.5143,
          0.9589],
        [ 0.5193,  0.2695,  0.9072,  0.4709,  0.3497,  0.6431,  0.6209,
          0.3219]])

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## Getting element in tensor - ` .item() `<a class="anchor" id="fifth-bullet"></a>

In [43]:
x_new3 = torch.rand(1)
print(x_new3)
print(x_new3.item())
print()

x_new4 = torch.rand(1,3)
print(x_new4)
for tens in x_new4:
    for ten in tens:
        print(ten)
        print(ten.item())
        print()

tensor([ 0.4049])
0.4049144387245178

tensor([[ 0.2679,  0.3810,  0.9067]])
tensor(0.2679)
0.2679094672203064

tensor(0.3810)
0.3809683918952942

tensor(0.9067)
0.9066909551620483



## Converting from tensor to NumPy Array, vice versa <a class="anchor" id="sixth-bullet"></a>

In [48]:
a = np.ones(5)
b = torch.from_numpy(a)

print("a")
print(a)
print()
print("b")
print(b)
print()

c = b.numpy()
print("c")
print(c)

a
[1. 1. 1. 1. 1.]

b
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)

c
[1. 1. 1. 1. 1.]


## Using GPU ` .to` method <a class="anchor" id="seventh-bullet"></a>

In [60]:
if torch.cuda.is_available():
    
    print("GPU is available")
    print()
    
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    print("Devide y is on : %s"%(y.device))
    print()
    
    x = x.to(device)                       
    
    z = x + y
    
    print("Before moving z to CPU")
    print(z)
    print("Device : %s"%z.device)
    print()
    
    print("After moving z to CPU")
    z = z.to("cpu", torch.double) # or just use strings ``.to("cuda")``
    print(z)       # ``.to`` can also change dtype together!
    print("Device : %s"%z.device)

GPU is available

Devide y is on : cuda:0

Before moving z to CPU
tensor([ 1.2253,  1.4826,  1.9240,  1.3496,  1.4778], device='cuda:0')
Device : cuda:0

After moving z to CPU
tensor([ 1.2253,  1.4826,  1.9240,  1.3496,  1.4778], dtype=torch.float64)
Device : cpu
